# Generated by Django 3.1.7 on 2021-03-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
                ('skills', models.ManyToManyField(to='mainapp.Skill')),
            ],
        ),
    ]
